# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6f5d10e5294e2e2b3cb3047fb1b19ca20502bab9534faa2ebb0bd8f9bbb80ee3723e45ac3c294c1544808978c3ec33ff25da21219fc381bf4432431e6d576e4

test:
  secret_key_base: 1ec18324ecf084d49a3ac166e190bdb490be6ed0e20e28a6c34404d487c5ac90f8c4660c34900c61e0139b42acc540cfbc36166308fe0c6522be27d12179d73f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
